---
# Docker role default variables

# Docker daemon configuration
docker_log_driver: "json-file"
docker_log_max_size: "10m"
docker_log_max_file: "3"
docker_storage_driver: "overlay2"
docker_userland_proxy: false

# User configuration
docker_users:
  - superdeploy
