---
# Forgejo Runner defaults
forgejo_runner_version: "3.5.0"
forgejo_port: 3001  # Default port, can be overridden from project config
superdeploy_user: "superdeploy"
superdeploy_group: "superdeploy"
