---
# Monitoring role handlers

- name: reload prometheus
  uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    status_code: 200
  ignore_errors: yes
  listen: reload prometheus

- name: restart grafana
  docker_container:
    name: superdeploy-grafana
    state: started
    restart: yes
  ignore_errors: yes
  listen: restart grafana
