project:
  name: cheapa
  description: cheapa project
  created_at: '2025-11-11T23:50:00.000000'
  ssl_email: admin@cheapa.io
cloud:
  gcp:
    project_id: galvanic-camp-475519-d6
    region: us-central1
    zone: us-central1-a
  ssh:
    key_path: ~/.ssh/superdeploy_deploy
    public_key_path: ~/.ssh/superdeploy_deploy.pub
    user: superdeploy
vms:
  core:
    count: 1
    machine_type: e2-medium
    disk_size: 20
    services:
    - rabbitmq
    - postgres
  app:
    count: 1
    machine_type: e2-medium
    disk_size: 30
    services: []
addons:
  databases:
    primary:
      type: postgres
      version: 15-alpine
      plan: standard
      port: 5432
      vm: core
      options: {}
  queues:
    primary:
      type: rabbitmq
      version: 3.12-management-alpine
      plan: standard
      port: 5672
      management_port: 15672
      vm: core
      options: {}
  proxy:
    primary:
      type: caddy
      version: 2-alpine
      plan: standard
      http_port: 80
      https_port: 443
      admin_port: 2019
      vm: app
      options: {}
apps:
  api:
    path: /Users/cfkarakulak/Desktop/cheapa.io/code/api
    vm: app
    port: 8000
  services:
    path: /Users/cfkarakulak/Desktop/cheapa.io/code/services
    vm: app
    port: null
  storefront:
    path: /Users/cfkarakulak/Desktop/cheapa.io/code/storefront
    vm: app
    port: 3000
docker:
  registry: docker.io
  organization: c100394
github:
  organization: cheapaio
network:
  vpc_subnet: 10.1.0.0/16
  docker_subnet: 172.30.0.0/24
